import sqlite3


class Settings:

	#GAME SETTINGS
	TITLE = "FLAPPY BIRD"
	CONN = sqlite3.connect("data/app.db")
	CUR = CONN.cursor()

	#SCREEN SETTINGS
	BASE = 40
	RATIO = (16, 9)
	SCREEN_WIDTH = BASE*RATIO[1]
	SCREEN_HEIGHT = BASE*RATIO[0]
	BG_SCREEN = "images/bg.png"


	#PLATFORM SETTINGS
	PLATFORM_IMG = "images/land.png"
	PLATFORM_SPEED = 5


	#PIPE SETTINGS
	PIPE_WIDTH = SCREEN_WIDTH//6
	PIPE_HEIGHT = SCREEN_HEIGHT//2
	PIPE_COLOR = (60, 60, 60)
	PIPE_SPEED = 5


	#BIRD SETTINGS
	BIRD_IMG = "images/bird.png"
	BIRD_FLY_SPEED = 5
	BIRD_FALL_SPEED = 3
	BIRD_LIFE = 3


	#SCOREBOARD SETTINGS
	FONT = "fonts/AGOXES_GAME.otf"
	FONT_SIZE = 40
	FONT_COLOR = (242, 255, 0)


	#BUTTON SETTINGS
	BUTTON_WIDTH = 200
	BUTTON_HEIGHT = 50
	BUTTON_COLOR = (122, 255, 0)
	BUTTON_FONT = "fonts/AGOXES_GAME.otf"
	BUTTON_FONT_SIZE = 30
	BUTTON_FONT_COLOR = (255, 255, 255)

	#LABEL SETTINGS
	LABEL_FONT = "fonts/AGOXES_GAME.otf"
	LABEL_FONT_SIZE = 30
	LABEL_FONT_COLOR = (255, 255, 255)


	#ENTRY SETTINGS
	ENTRY_HEIGHT = 50
	ENTRY_COLOR_ACTIVE = (255, 0, 0)
	ENTRY_COLOR_INACTIVE = (122, 255, 0)
	ENTRY_FONT = "fonts/28_Days_Later.ttf"
	ENTRY_FONT_SIZE = 30
	ENTRY_FONT_COLOR = (255, 255, 255)





